// firebase_options.dart 변환
// File generated by FlutterFire CLI. (원본 유지)
import Foundation
import FirebaseCore

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// 사용 예:
/// ```swift
/// FirebaseApp.configure(options: DefaultFirebaseOptions.currentPlatform)
/// ```
enum DefaultFirebaseOptions {
    /// 현재 플랫폼(iOS)용 옵션.
    /// 원본 Dart는 defaultTargetPlatform 분기였으나, 네이티브 iOS 앱이므로 ios를 반환.
    static var currentPlatform: FirebaseOptions {
        return ios
    }

    static var ios: FirebaseOptions {
        let options = FirebaseOptions(
            googleAppID: "1:686539632718:ios:8f3985bd05ae84741b131f",
            gcmSenderID: "686539632718"
        )
        options.apiKey = "AIzaSyBYtXBxmXeKiqDzK5VPyDKUnOjtzBHj7BE"
        options.projectID = "alarmit--uou"
        options.storageBucket = "alarmit--uou.firebasestorage.app"
        options.bundleID = "com.uou.alarmit"
        return options
    }

    static var macos: FirebaseOptions {
        let options = FirebaseOptions(
            googleAppID: "1:686539632718:ios:4cae07de119c97581b131f",
            gcmSenderID: "686539632718"
        )
        options.apiKey = "AIzaSyBYtXBxmXeKiqDzK5VPyDKUnOjtzBHj7BE"
        options.projectID = "alarmit--uou"
        options.storageBucket = "alarmit--uou.firebasestorage.app"
        options.bundleID = "com.example.notificationIt"
        return options
    }

    static var android: FirebaseOptions {
        let options = FirebaseOptions(
            googleAppID: "1:686539632718:android:6ca0959b22f2fdc31b131f",
            gcmSenderID: "686539632718"
        )
        options.apiKey = "AIzaSyC-UJb4CtxPopiJrAKodbwnEi4bCawV4Is"
        options.projectID = "alarmit--uou"
        options.storageBucket = "alarmit--uou.firebasestorage.app"
        return options
    }

    static var web: FirebaseOptions {
        let options = FirebaseOptions(
            googleAppID: "1:686539632718:web:90a9ce7dee9ea89c1b131f",
            gcmSenderID: "686539632718"
        )
        options.apiKey = "AIzaSyBpEUJxmYleRUeFDlg9aLE6RcScsoByiy0"
        options.projectID = "alarmit--uou"
        options.storageBucket = "alarmit--uou.firebasestorage.app"
        return options
    }

    static var windows: FirebaseOptions {
        let options = FirebaseOptions(
            googleAppID: "1:686539632718:web:8c9b43adf3ec51b01b131f",
            gcmSenderID: "686539632718"
        )
        options.apiKey = "AIzaSyBpEUJxmYleRUeFDlg9aLE6RcScsoByiy0"
        options.projectID = "alarmit--uou"
        options.storageBucket = "alarmit--uou.firebasestorage.app"
        return options
    }
}
